Inbound Call and OAuth Example
signalwire/call-fabric-client-beta pull request #4
Opened 2023-12-04 13:10 UTC by jpsantosbh

* Fix the server-side token request to include the application-id 
* Adds the invite via push notification flow to the *Full* example use-case.
* Adds a OAuth flow request token exemple

2023-12-04 16:13 UTC, iAmmar7 requested changes

2023-12-04 16:13 UTC, iAmmar7 commented on public/full.js
> +  // console.log('key', key)
```suggestion
```

2023-12-04 16:13 UTC, iAmmar7 commented on public/full.js
> +  // console.log('iv', iv)
```suggestion
```

2023-12-04 16:13 UTC, iAmmar7 commented on public/full.js
> +  // console.log('fullEncrypted', fullEncrypted)
```suggestion
```

2023-12-04 16:13 UTC, iAmmar7 commented on public/full.js
> +  // console.log('compressed', compressed)
```suggestion
```

2023-12-04 16:13 UTC, iAmmar7 commented on views/minimal.ejs
> +  <script type="text/javascript" src="https://unpkg.com/@signalwire/js@dev"></script>
Same as above

2023-12-04 16:28 UTC, jpsantosbh commented on views/index.ejs
> +  <script type="text/javascript" src="https://unpkg.com/@signalwire/js@dev"></script>
The demo is using the Call Fabric Browser SDK, not been released yet.

2023-12-06 15:02 UTC, iAmmar7 commented on views/index.ejs
> +  <script type="text/javascript" src="https://unpkg.com/@signalwire/js@dev"></script>
Call Fabric has already been released, you can use it without the dev tag.

2023-12-06 15:51 UTC, jpsantosbh commented on views/index.ejs
> +  <script type="text/javascript" src="https://unpkg.com/@signalwire/js@dev"></script>
True, I was missing that thanks

2023-12-07 09:42 UTC, iAmmar7 approved these changes

2023-12-07 11:06 UTC, merged