Add members view to the UI
signalwire/call-fabric-client-beta pull request #47
Opened 2024-02-16 00:50 UTC by jpsantosbh

![Signalwire_Call_Demo](https://github.com/signalwire/call-fabric-client-beta/assets/1903302/2997d21f-6863-452a-aaea-c80de7399782)

2024-02-19 10:09 UTC, jpsantosbh commented
This depends on https://github.com/signalwire/signalwire-js/pull/968

2024-02-19 11:13 UTC, iAmmar7 requested changes

2024-02-19 11:13 UTC, iAmmar7 commented on public/index.umd.js
> +/workspaces/signalwire-js/packages/js/dist/index.umd.js
You have mistakenly pushed the build files.

2024-02-19 11:13 UTC, iAmmar7 commented on views/index.ejs
> -  <script src="/full.js"></script>
Same as above, probably you forgot to undo these development setups.

2024-02-19 11:13 UTC, iAmmar7 commented on views/index.ejs
> +          </ul>
Just to have consistent code comments for readability.

```suggestion

          <!-- Member List UI -->
          <ul class="col-4 list-group" id="members"></ul>
          <!-- Member List UI end -->
```

2024-03-11 17:29 UTC, ryanwi approved these changes

2024-03-12 10:22 UTC, jpsantosbh commented on public/full.js
> +  const startCall = async () => new Promise(async (res, rej) => {
I was just a rename, reverted

2024-03-12 10:22 UTC, jpsantosbh commented on public/full.js
> +  await startPromise
reverted

2024-03-12 13:37 UTC, iAmmar7 approved these changes

2024-03-12 13:38 UTC, merged